-- Migration 137: Comment the Five Views That Still Have No Comment (issue #819)
--
-- Slice E of #819. config/schema_docs_baseline.json keeps 34 entries after
-- migrations 135 and 136; five of them are views with no comment on
-- NEXUS_template or save_01..save_05 (obj_description is NULL on all six
-- databases, read on 2026-09-30): chunk_entity_references_v, entity_names_v,
-- entity_relationships_v, entity_tags_current, and incubator_view. Each
-- comment below says what one row means, what the view is derived from, and
-- which code reads it; each clause rests on the view definition or on a
-- reader or writer site listed below. The same change removes the five
-- view:public.* baseline entries (34 - 5 = 29 remain).
--
-- The live definitions are identical on NEXUS_template and save_01..save_05
-- (md5 of pg_get_viewdef) and match the migrations that last defined them:
-- chunk_entity_references_v and entity_names_v migrations/023_orrery_schema.py:407-434;
-- entity_relationships_v migrations/088_valence_float_canonical.sql:151-198;
-- entity_tags_current migrations/064_tag_provenance_forward_fix.sql:52-70;
-- incubator_view migrations/041_orrery_authority_model.sql:40-68.
-- scripts/create_incubator_table.sql:70 holds an older incubator_view comment
-- that no database carries; its one checkable clause (parent chunk context)
-- holds for today's definition and is kept below.
--
-- Comment-only and idempotent: COMMENT ON replaces the previous text, so
-- rerunning this file leaves the same documentation. No objects are created
-- or changed.
--
-- Evidence sites (code at c8dd8c85).
-- chunk_entity_references_v: definition (023_orrery_schema.py:423-434); chunk_faction_references has no role column and place_chunk_references is keyed (place_id, chunk_id, reference_type) with an evidence column (catalog, NEXUS_template); readers scripts/orrery_sample.py:233-263 and no file under nexus/ (git grep)
-- entity_names_v: definition (023_orrery_schema.py:407-421); characters, factions, and places each have UNIQUE (entity_id) (catalog); readers nexus/agents/orrery/events.py:803,1092,1553-1570 (commit_orrery_tick_sync); nexus/agents/orrery/resolver.py:2677-2684,3443-3458; nexus/agents/orrery/worker.py:176-205,235-286; nexus/agents/orrery/bleed.py:196-250,415-436; nexus/agents/orrery/experiences.py:647,720-752,438-439; nexus/agents/orrery/relationship_provenance.py:427-452; nexus/agents/orrery/experiences.py:1133-1226,1350-1355,1381-1382,1403-1405,2080; nexus/agents/orrery/retrograde_persistence.py:192,276,2725-2742
-- entity_relationships_v: definition (088_valence_float_canonical.sql:151-198); readers, all WHERE relationship_scope = 'character': nexus/agents/orrery/resolver.py:383-413 (_load_orbit_distances), 646-668 (hydrate_world_state, relationship types and trust), 1011-1034 (_load_character_relationship_pairs); nexus/agents/orrery/reveal.py:387,410,423-432 (_TRUST_SQL); nexus/agents/orrery/knowledge_surfacing.py:659-689 (_disclosure_context); nexus/agents/orrery/audit.py:2022-2031,2162-2178 (entity_context); membership loader reads the table directly: nexus/agents/orrery/resolver.py:694-708; agrees with migrations/136_column_comment_corrections.sql:46-50
-- entity_tags_current: definition (064_tag_provenance_forward_fix.sql:52-70); unique index ix_entity_tags_current ON entity_tags (entity_id, tag_id) WHERE cleared_at IS NULL (catalog); expiry sweep sets cleared_at: nexus/agents/orrery/events.py:7944-7967 (_sweep_expired_entity_tags_sync); every reader joins entity_tags on entity_tag_id and tests expires_at_world_time: nexus/agents/orrery/resolver.py:446-475,595-612,1320,1389-1403; nexus/agents/orrery/tag_activity.py:6-24; nexus/agents/orrery/events.py:5582-5594,5708-5760,6953-6990,7005-7030,7111-7146,7158-7182; nexus/agents/orrery/communication.py:64-78; nexus/agents/orrery/audit.py:2067-2083,2388-2403; nexus/api/faction_table_audit.py:794-815; nexus/agents/lore/utils/entity_queries.py:29-70,82,102,323,339; scripts/orrery_sample.py:195-210
-- incubator_view: definition (041_orrery_authority_model.sql:40-68); incubator singleton CHECK (id = true) (catalog); entity_updates shape nexus/agents/logon/apex_schema.py:531-547 via nexus/api/lore_adapter.py:337-341; metadata_updates writers nexus/api/lore_adapter.py:184,290-335 and nexus/api/narrative_generation.py:641,852-861 (no pacing key); correspondence letters absent: tests/test_api/test_backstage_endpoints_pg.py:712-730; readers nexus/api/narrative.py:1619-1638 (GET /api/narrative/incubator) and nexus/cli.py:1459-1472,5036 (nexus inspect incubator)

COMMENT ON VIEW public.chunk_entity_references_v IS
    'Chunk references of characters, factions, and places in one shape: one row for each row of chunk_character_references, chunk_faction_references, and place_chunk_references, carrying its chunk_id and the entity_id of the referenced character, faction, or place. reference_type is chunk_character_references.reference or place_chunk_references.reference_type cast to text, and is NULL on every faction row, because chunk_faction_references has no role column. place_chunk_references keys its rows by place, chunk, and reference type, so one place can have several rows for one chunk. The view carries no entity kind and leaves out place_chunk_references.evidence. No code under nexus/ reads it; the Orrery dry-run sampler (scripts/orrery_sample.py) takes the first referencing chunk of each entity from it.';

COMMENT ON VIEW public.entity_names_v IS
    'Name of each character, faction, and place entity: one row for each entities row of kind character, faction, or place that has a characters, factions, or places row of the same kind, carrying the entity id, the kind, and the name from that row. Orrery code joins it to put names on entity ids: the commit tick for proposal entities, the resolver for draft bindings, the resolution promotion and narration drains for resolution actors, bleed for resolution actors and event targets, experience seeding for world event actors and targets, and relationship provenance for claim participants. Experience rendering reads every name and rejects a rendered experience that names a known entity its seed does not allow, and Retrograde persistence builds its entity catalog from the view.';

COMMENT ON VIEW public.entity_relationships_v IS
    'Relationship edges between entities in one shape: one row for each row of character_relationships (relationship_scope character, source character1, target character2), faction_relationships (scope faction, source faction1, target faction2), and faction_character_relationships (scope faction_character, source the faction, target the character), with both ends mapped to entity ids. relationship_type carries the character relationship type, the faction relationship type, or the member role as text; dynamic carries dynamic in character scope and current_status in the other two; valence, recent_events, valence_magnitude, and valence_current are NULL outside character scope. Every reader under nexus/ selects character scope only: the Orrery resolver (orbit distances, relationship types and trust, actor-target bindings), secret reveal (trust), knowledge surfacing (valence between characters), and the audit entity hover. The resolver faction membership loader reads faction_character_relationships directly, not this view.';

COMMENT ON VIEW public.entity_tags_current IS
    'Uncleared tag applications: one row for each entity_tags row whose cleared_at is NULL and whose tag is neither deprecated nor a synonym (tags.synonym_for NULL), carrying the tag name, category, ephemeral flag, and clearance kind from tags, the entity kind, and the application provenance (applied_at, applied_at_world_time, source_kind, template_id, source_chunk_id). A partial unique index on entity_tags allows at most one such row per entity and tag. The view applies no expiry test: a tag whose expires_at_world_time has passed stays here until a clear, such as the expiry sweep, sets cleared_at. Every reader under nexus/ and scripts/ joins entity_tags on entity_tag_id and applies its own expires_at_world_time test: the Orrery resolver (current tags, place location classes, actors with ephemeral tags), need applicability and routine destination choice in the Orrery events module, communication culture tags, the audit entity hover, the faction table audit, and the character and faction dossiers of the turn context.';

COMMENT ON VIEW public.incubator_view IS
    'The pending draft with its parent chunk text: at most one row, from the singleton incubator row (id true), with narrative_chunks.raw_text of parent_chunk_id as parent_chunk_text through a left join. It passes through chunk_id, parent_chunk_id, user_text, storyteller_text, choice_object, choice_text, authorial_directives, orrery_proposal, orrery_adjudications, status, session_id, and created_at; lifts episode_transition and time_delta_description (as time_delta) from metadata_updates.chronology, and world_layer and pacing from metadata_updates, although no current writer sets pacing; renames entity_updates to entity_changes and reference_updates to references; and counts entity_update_count as the lengths of the characters, locations, and factions arrays of entity_updates, leaving out its relationships array. It leaves out metadata_updates itself, new_entities, generation_model, llm_response_id, updated_at, lore_pass_baseline, and both staged correspondence letters. GET /api/narrative/incubator returns its row, filtered by session_id when one is given, and nexus inspect incubator reads that endpoint.';
