"""Render the Orrery package catalog as human-readable markdown.

The templates in nexus/agents/orrery/templates.py are the canonical
source-of-truth for behavior package definitions. This module introspects
them and emits a structured markdown catalog (docs/orrery_packages.md)
that's easier to read at a glance — for narrative authors drafting new
templates, for reviewers auditing the catalog, and for future contributors
checking what vocabulary is already represented.

The renderer relies on two introspection surfaces:

- ``CompoundCondition`` (substrate.py) exposes ``.op`` and ``.children``
  for AND / OR / NOT, letting the renderer walk gate trees recursively.
- Leaf predicates carry their construction arguments in ``__name__``,
  which the renderer parses back to prose via a regex dispatch table.

Usage:
    python -m nexus.agents.orrery.catalog                # render to stdout
    python -m nexus.agents.orrery.catalog --write        # update docs/
    python -m nexus.agents.orrery.catalog --check        # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any, Callable, Iterable, List, Mapping, Tuple

from nexus.agents.orrery.substrate import (
    Branch,
    CompoundCondition,
    Template,
    drive_band_priority_warnings,
)
from nexus.agents.orrery.templates import BUILTIN_TEMPLATES


AUTO_GEN_HEADER = (
    "<!-- AUTO-GENERATED by nexus.agents.orrery.catalog "
    "— do not edit by hand. -->\n"
    "<!-- Regenerate via: python -m nexus.agents.orrery.catalog --write -->"
)


# ---------------------------------------------------------------------------
# Predicate name → prose dispatch
# ---------------------------------------------------------------------------

_PREDICATE_PARSERS: List[Tuple[re.Pattern, Callable[[re.Match], str]]] = []


def _register(pattern: str, formatter: Callable[[re.Match], str]) -> None:
    _PREDICATE_PARSERS.append((re.compile(pattern), formatter))


def _slot(value: str) -> str:
    """Render a Slot.value string as lowercase prose."""

    return value.lower()


def _render_travel_purpose_predicate(match: re.Match) -> str:
    """Render travel_purpose_is(...) with singular/plural purpose wording."""

    purposes = [item for item in match.group("purpose").split(",") if item]
    rendered = ", ".join(f"`{purpose}`" for purpose in purposes)
    noun = "purpose" if len(purposes) == 1 else "purposes"
    return f"{_slot(match.group('slot'))} is traveling for {rendered} {noun}"


# Tag predicates
_register(
    r"has_tag\((?P<tag>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} has `{m.group('tag')}` tag",
)
_register(
    r"lacks_tag\((?P<tag>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} lacks `{m.group('tag')}` tag",
)
_register(
    r"has_any_tag\((?P<tags>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} has any of ["
        + ", ".join(f"`{t}`" for t in m.group("tags").split(","))
        + "]"
    ),
)
_register(
    r"has_any_current_tag\((?P<tags>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} has any current tag of ["
        + ", ".join(f"`{t}`" for t in m.group("tags").split(","))
        + "]"
    ),
)
_register(
    r"has_pair_tag\((?P<tag>[^@()]+)@(?P<subj>\w+)->(?P<obj>\w+)\)",
    lambda m: (
        f"{_slot(m.group('subj'))} has `{m.group('tag')}` pair tag "
        f"to {_slot(m.group('obj'))}"
    ),
)
_register(
    r"lacks_pair_tag\((?P<tag>[^@()]+)@(?P<subj>\w+)->(?P<obj>\w+)\)",
    lambda m: (
        f"{_slot(m.group('subj'))} lacks `{m.group('tag')}` pair tag "
        f"to {_slot(m.group('obj'))}"
    ),
)
_register(
    r"has_any_pair_tag\((?P<tags>[^@()]+)@(?P<subj>\w+)->(?P<obj>\w+)\)",
    lambda m: (
        f"{_slot(m.group('subj'))} has any of ["
        + ", ".join(f"`{t}`" for t in m.group("tags").split(","))
        + f"] pair tags to {_slot(m.group('obj'))}"
    ),
)
_register(
    r"has_pair_tag_to_current_location\((?P<tag>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} has `{m.group('tag')}` pair tag "
        "to current location"
    ),
)
_register(
    r"has_inbound_pair_tag\((?P<tag>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (f"{_slot(m.group('slot'))} has inbound " f"`{m.group('tag')}` pair tag"),
)
_register(
    r"has_contact_of_kind\((?P<kind>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} has outbound "
        f"`contact:{m.group('kind')}` pair tag"
    ),
)
_register(
    r"has_ephemeral\((?P<tag>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} has `{m.group('tag')}` ephemeral",
)
_register(
    r"has_minimal_context\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} has enough hydrated context",
)
_register(
    r"is_constrained\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is constrained or immobilized",
)
_register(
    r"is_hidden\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is hidden or off-grid",
)
_register(
    r"can_move_publicly\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} can plausibly move through public flow",
)
_register(
    r"has_any_intimacy_suppressor\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} has an intimacy suppressor",
)
_register(
    r"has_severity_tag\((?P<prefix>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} has `{m.group('prefix')}` severity",
)
_register(
    r"has_severity_tag_at_or_above\("
    r"(?P<prefix>[^,()]+),(?P<level>\d+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} has `{m.group('prefix')}` severity "
        f"level {m.group('level')}+"
    ),
)
_register(
    r"has_need_debt_at_or_above\("
    r"(?P<need>[^,()]+),(?P<threshold>[\d.]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} has `{m.group('need')}` debt ≥ "
        f"{m.group('threshold')}"
    ),
)

# Self-awareness predicates (issue #282): stage-2 reads of the acting
# entity's own fame / resources tiers and self-scoped status edges.
_register(
    r"fame_at_or_above\((?P<tier>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (f"{_slot(m.group('slot'))}'s own fame is `{m.group('tier')}` or wider"),
)
_register(
    r"fame_below\((?P<tier>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))}'s own fame is narrower than `{m.group('tier')}`"
    ),
)
_register(
    r"resources_at_or_above\((?P<tier>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))}'s own resources are `{m.group('tier')}` or better"
    ),
)
_register(
    r"resources_below\((?P<tier>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))}'s own resources are below `{m.group('tier')}`"
    ),
)
_register(
    r"has_any_status_at_or_above\((?P<level>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} holds `status:{m.group('level')}`+ "
        "toward any faction"
    ),
)

# Location predicates
_register(
    r"in_location_class\((?P<lc>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is in `{m.group('lc')}` place class",
)
_register(
    r"has_location_class_destination\((?P<lc>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} can resolve a destination with place class "
        f"`{m.group('lc')}`"
    ),
)
_register(
    r"in_location\((?P<lid>\d+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is at location id `{m.group('lid')}`",
)
_register(
    r"co_located\((?P<a>\w+),(?P<b>\w+)\)",
    lambda m: f"{_slot(m.group('a'))} and {_slot(m.group('b'))} are co-located",
)
_register(
    r"count_co_located\((?P<n>\d+)@(?P<slot>\w+)"
    r"(?:,tag=(?P<tag>[^,)]+))?"
    r"(?:,ephemeral=(?P<ephemeral>[^,)]+))?\)",
    lambda m: (
        f"{m.group('n')}+ other entities"
        + (f" with `{m.group('tag')}` tag" if m.group("tag") else "")
        + (f" with `{m.group('ephemeral')}` ephemeral" if m.group("ephemeral") else "")
        + f" co-located with {_slot(m.group('slot'))}"
    ),
)
_register(
    r"has_established_partner_co_located\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} has an established partner co-located",
)
_register(
    r"is_in_transit\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is in transit",
)
_register(
    r"has_travel_destination\(@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} has a planned travel destination",
)
_register(
    r"travel_purpose_is\((?P<purpose>[^@()]+)@(?P<slot>\w+)\)",
    _render_travel_purpose_predicate,
)
_register(
    r"has_routine_anchor\((?P<anchor>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (f"{_slot(m.group('slot'))} has `{m.group('anchor')}` routine anchor"),
)
_register(
    r"routine_anchor_due\((?P<anchor>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))}'s `{m.group('anchor')}` routine is due now "
        "(weekdays 0=Monday; empty schedule always due)"
    ),
)
_register(
    r"at_routine_anchor\((?P<anchor>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is at `{m.group('anchor')}` anchor",
)
_register(
    r"away_from_routine_anchor\((?P<anchor>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is away from `{m.group('anchor')}` anchor",
)
_register(
    r"routine_anchor_has_destination\((?P<anchor>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))}'s `{m.group('anchor')}` routine "
        "can resolve a destination"
    ),
)
_register(
    r"travel_progress_at_or_above\((?P<threshold>[\d.]+)@(?P<slot>\w+)\)",
    lambda m: (f"{_slot(m.group('slot'))} travel progress ≥ {m.group('threshold')}"),
)
_register(
    r"travel_risk_is\((?P<values>[^@()]+)@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} travel risk is one of "
        f"[{', '.join(m.group('values').split(','))}]"
    ),
)

# Trust predicates
_register(
    r"trust_at_least\((?P<thresh>-?\d+),(?P<a>\w+)->(?P<b>\w+)\)",
    lambda m: (
        f"trust {_slot(m.group('a'))}→{_slot(m.group('b'))} ≥ {m.group('thresh')}"
    ),
)
_register(
    r"trust_below\((?P<thresh>-?\d+),(?P<a>\w+)->(?P<b>\w+)\)",
    lambda m: (
        f"trust {_slot(m.group('a'))}→{_slot(m.group('b'))} < {m.group('thresh')}"
    ),
)
_register(
    r"relationship_is_mutual_warm\((?P<a>\w+)<->(?P<b>\w+)\)",
    lambda m: (
        f"{_slot(m.group('a'))} and {_slot(m.group('b'))} have mutual warm trust"
    ),
)
_register(
    r"relationship_is_asymmetric\((?P<thresh>\d+),(?P<a>\w+)<->(?P<b>\w+)\)",
    lambda m: (
        f"directional trust {_slot(m.group('a'))}↔{_slot(m.group('b'))} "
        f"differs by {m.group('thresh')}+ or is loaded"
    ),
)
_register(
    r"direct_contact_is_dramatic\((?P<a>\w+)->(?P<b>\w+)\)",
    lambda m: (
        f"direct contact {_slot(m.group('a'))}→{_slot(m.group('b'))} is dramatic"
    ),
)

# Relationship predicates
_register(
    r"has_relationship_of_type\((?P<type>[^,()]+),(?P<from>\w+)->(?P<to>\w+)\)",
    lambda m: (
        f"{_slot(m.group('from'))} has `{m.group('type')}` relationship "
        f"to {_slot(m.group('to'))}"
    ),
)
_register(
    r"has_symmetric_relationship_of_type\("
    r"(?P<type>[^,()]+),(?P<a>\w+)<->(?P<b>\w+)\)",
    lambda m: (
        f"{_slot(m.group('a'))} and {_slot(m.group('b'))} share "
        f"`{m.group('type')}` relationship (either direction)"
    ),
)
_register(
    r"faction_member\((?P<member>\w+)->(?P<faction>\w+)\)",
    lambda m: (
        f"{_slot(m.group('member'))} is a member of faction "
        f"{_slot(m.group('faction'))}"
    ),
)
_register(
    r"relative_orbit_distance\(<=(?P<n>\d+),(?P<a>\w+)->(?P<b>\w+)\)",
    lambda m: (
        f"social orbit distance {_slot(m.group('a'))}→{_slot(m.group('b'))}"
        f" ≤ {m.group('n')}"
    ),
)

# Time / weather predicates
_register(
    r"time_of_day_in\((?P<values>[^)]+)\)",
    lambda m: f"time of day is one of [{', '.join(m.group('values').split(','))}]",
)
_register(
    r"weather_is\((?P<values>[^)]+)\)",
    lambda m: f"weather is one of [{', '.join(m.group('values').split(','))}]",
)


# Event predicates (multi-arg, need custom formatters)
def _render_recent_event(m: re.Match) -> str:
    event = m.group("event")
    n = m.group("n")
    actor = m.group("actor")
    target = m.group("target")
    parts = ["any event" if event == "*" else f"`{event}` event"]
    if actor:
        parts.append(f"with actor={_slot(actor)}")
    if target:
        parts.append(f"targeting {_slot(target)}")
    return f"recent {' '.join(parts)} in last {n} ticks"


def _render_knows_recent_event(m: re.Match) -> str:
    event = m.group("event")
    n = m.group("n")
    actor = m.group("actor")
    target = m.group("target")
    parts = ["any event" if event == "*" else f"`{event}` event"]
    if actor:
        parts.append(f"with actor={_slot(actor)}")
    if target:
        parts.append(f"targeting {_slot(target)}")
    return f"actor knows recent {' '.join(parts)} in last {n} ticks"


def _render_since_last_event(m: re.Match) -> str:
    event = m.group("event")
    n = m.group("n")
    actor = m.group("actor")
    target = m.group("target")
    if target:
        scope = f"({_slot(actor)}, {_slot(target)}) pair"
    else:
        scope = _slot(actor)
    return f"≥ {n} ticks since last `{event}` event for {scope}"


_register(
    r"recent_event\((?P<event>[^,)]+),<=(?P<n>\d+)"
    r"(?:,actor=(?P<actor>\w+))?(?:,target=(?P<target>\w+))?(?:,fields)?\)",
    _render_recent_event,
)
_register(
    r"knows_recent_event\((?P<event>[^,)]+),<=(?P<n>\d+),knower=actor"
    r"(?:,actor=(?P<actor>\w+))?(?:,target=(?P<target>\w+))?(?:,fields)?\)",
    _render_knows_recent_event,
)
_register(
    r"since_last_event_at_least\("
    r"(?P<event>[^,()]+),(?P<n>\d+)@(?P<actor>\w+)"
    r"(?:,target=(?P<target>\w+))?\)",
    _render_since_last_event,
)

_register(
    r"project_due\((?P<project>[^,()]+),(?P<mode>[^@()]+)" r"@(?P<slot>\w+)\)",
    lambda m: (
        f"{_slot(m.group('slot'))} `{m.group('project')}` project "
        f"passes `{m.group('mode')}` due-state"
    ),
)
_register(
    r"project_target_is\((?P<slot>\w+)\)",
    lambda m: f"advancing recruitment of {_slot(m.group('slot'))}",
)
_register(
    r"project_target_is_active\((?P<slot>\w+)\)",
    lambda m: f"{_slot(m.group('slot'))} is the project's active-character recruit",
)


def _render_count_recent_events(m: re.Match) -> str:
    event = m.group("event")
    count = m.group("count")
    n = m.group("n")
    actor = m.group("actor")
    target = m.group("target")
    if target:
        scope = f"({_slot(actor)}, {_slot(target)}) pair"
    else:
        scope = _slot(actor)
    return f"≥ {count} `{event}` events within {n} ticks for {scope}"


_register(
    r"count_recent_events_at_least\("
    r"(?P<event>[^,()]+),>=(?P<count>\d+),<=(?P<n>\d+)@(?P<actor>\w+)"
    r"(?:,target=(?P<target>\w+))?\)",
    _render_count_recent_events,
)


def _render_predicate_name(name: str) -> str:
    """Convert a substrate ``__name__`` into prose-friendly text."""

    if name == "ALWAYS":
        return "*(always)*"
    if name == "NEVER":
        return "*(never)*"
    for pattern, formatter in _PREDICATE_PARSERS:
        match = pattern.fullmatch(name)
        if match:
            return formatter(match)
    return f"`{name}`  *(no prose renderer)*"


# ---------------------------------------------------------------------------
# Condition tree → markdown bullet lists
# ---------------------------------------------------------------------------


def _render_condition_lines(condition: Any, *, indent: int = 0) -> List[str]:
    """Render a condition as a list of markdown bullet lines."""

    pad = "  " * indent
    if isinstance(condition, CompoundCondition):
        if condition.op == "NOT":
            inner = condition.children[0]
            if isinstance(inner, CompoundCondition):
                return [
                    f"{pad}- **NOT:**",
                    *_render_condition_lines(inner, indent=indent + 1),
                ]
            inner_prose = _render_predicate_name(
                getattr(inner, "__name__", repr(inner))
            )
            return [f"{pad}- **NOT:** {inner_prose}"]
        header = f"{pad}- **{condition.op}:**"
        body: List[str] = []
        for child in condition.children:
            body.extend(_render_condition_lines(child, indent=indent + 1))
        return [header, *body]
    name = getattr(condition, "__name__", repr(condition))
    return [f"{pad}- {_render_predicate_name(name)}"]


def _render_condition_block(condition: Any) -> str:
    """Render a leaf condition as inline text; never call on compounds."""

    name = getattr(condition, "__name__", repr(condition))
    return _render_predicate_name(name)


# ---------------------------------------------------------------------------
# state_delta → compact prose
# ---------------------------------------------------------------------------


def _render_state_delta(delta: Mapping[str, Any]) -> str:
    parts: List[str] = []
    for key, value in delta.items():
        if key == "character.current_activity":
            parts.append(f'activity → "{value}"')
            continue
        if key in ("entity_tags.add", "entity_tags_target.add"):
            target = "actor" if key == "entity_tags.add" else "target"
            tags = ", ".join(f"`{t}`" for t in value)
            parts.append(f"adds {tags} to {target}")
            continue
        if key in ("entity_tags.remove", "entity_tags_target.remove"):
            target = "actor" if key == "entity_tags.remove" else "target"
            tags = ", ".join(f"`{t}`" for t in value)
            parts.append(f"removes {tags} from {target}")
            continue
        if key == "entity_pair_tags_target.clear_inbound":
            tags = ", ".join(f"`{t}`" for t in value)
            parts.append(f"clears inbound {tags} pair tags from target")
            continue
        if key == "entity_pair_tags.add_outbound":
            tags = ", ".join(f"`{t}`" for t in value)
            parts.append(f"adds outbound {tags} pair tag to target")
            continue
        if key == "entity_pair_tags.clear_outbound":
            tags = ", ".join(f"`{t}`" for t in value)
            parts.append(f"clears own outbound {tags} pair tag to target")
            continue
        if key == "need.fulfill":
            if isinstance(value, Mapping):
                need = value.get("type") or value.get("need")
                quality = value.get("quality")
                discharge = value.get("discharge_debt") or value.get("discharge")
                bits = [f"fulfills `{need}` need"]
                if quality:
                    bits.append(f"quality `{quality}`")
                if discharge is not None:
                    bits.append(f"discharge {discharge}")
                parts.append(", ".join(bits))
            else:
                parts.append(f"fulfills `{value}` need")
            continue
        if key == "travel.start":
            if isinstance(value, Mapping):
                destination_classes = (
                    value.get("destination_place_classes")
                    or value.get("destination_place_class")
                    or value.get("destination_class")
                )
                if destination_classes:
                    if isinstance(destination_classes, str):
                        destination = f"`{destination_classes}`"
                    else:
                        destination = ", ".join(
                            f"`{item}`" for item in destination_classes
                        )
                    parts.append(f"starts travel toward a {destination} destination")
                else:
                    parts.append("starts planned travel")
            else:
                parts.append("starts planned travel")
            continue
        if key == "travel.advance":
            progress = (
                value.get("progress_delta") if isinstance(value, Mapping) else None
            )
            if progress is None:
                parts.append("advances travel")
            else:
                parts.append(f"advances travel by {progress}")
            continue
        if key == "travel.arrive":
            parts.append("arrives at travel destination")
            continue
        if key == "travel.delay":
            parts.append("records travel delay")
            continue
        if key.startswith("project."):
            transition = key.removeprefix("project.")
            parts.append(f"applies project `{transition}` transition")
            continue
        parts.append(f"`{key}` = `{value}`")
    return "; ".join(parts)


# ---------------------------------------------------------------------------
# Branch and template rendering
# ---------------------------------------------------------------------------


def _render_narrative_stub(stub: str) -> List[str]:
    return ["> " + line if line else ">" for line in stub.split("\n")]


def _render_branch(idx: int, branch: Branch) -> List[str]:
    markers = []
    if branch.preemptive:
        markers.append("**preemptive**")
    if not branch.promotable:
        markers.append("**not promotable**")
    marker = f" · {' · '.join(markers)}" if markers else ""
    lines = [
        f"### Branch {idx} — {branch.label}  *(mag {branch.magnitude})*{marker}",
        "",
    ]
    if isinstance(branch.conditions, CompoundCondition):
        lines.extend(["**When:**", ""])
        lines.extend(_render_condition_lines(branch.conditions))
    else:
        lines.append(f"**When:** {_render_condition_block(branch.conditions)}")
    lines.append("")
    if branch.state_delta:
        lines.append(f"**Does:** {_render_state_delta(branch.state_delta)}")
    if branch.event_type:
        lines.append(f"**Event:** `{branch.event_type}`")
    if branch.narrative_stub:
        lines.append("")
        lines.extend(_render_narrative_stub(branch.narrative_stub))
    scene_stub = getattr(branch, "scene_pressure_stub", None)
    if scene_stub:
        lines.append("")
        lines.append(
            "**Scene-pressure prompt** (storyteller-LLM-only; no " "state mutation):"
        )
        lines.append("")
        lines.extend(_render_narrative_stub(scene_stub))
    return lines


def _render_present_target_policy(template: Template) -> str | None:
    """Render the present-target policy as prose, or None if default/missing."""

    policy = getattr(template, "present_target_policy", None)
    if policy is None:
        return None
    value = getattr(policy, "value", str(policy))
    if value == "offscreen_only":
        return None  # default — omit to keep the catalog terse
    if value == "storyteller_pressure":
        return (
            "may target an on-screen entity — but only as a prompt-only "
            "scene-pressure draft routed through storyteller LLM review "
            "(no direct state mutation, no canonical event)"
        )
    return f"`{value}`"


def _render_drive_band(template: Template) -> str:
    """Render one template's drive band and any priority rationale."""

    value = template.drive_band.value.replace("_", " ")
    if template.drive_band_priority_exempt:
        if not template.priority_override_rationale:
            return f"{value} — priority-order exempt"
        return (
            f"{value} — priority-order exempt: {template.priority_override_rationale}"
        )
    if not template.priority_override_rationale:
        return value
    return f"{value} — {template.priority_override_rationale}"


def _render_template(template: Template) -> List[str]:
    slots = ", ".join(s.value.upper() for s in template.required_slots)
    lines = [
        f"## {template.id.upper()} — priority {template.priority}",
        "",
        f"> {template.blurb}",
        "",
        f"**Drive band:** {_render_drive_band(template)}",
        f"**Slots:** {slots}",
    ]
    policy_prose = _render_present_target_policy(template)
    if policy_prose:
        lines.append(f"**Present-target policy:** {policy_prose}")
    lines.append("")
    if isinstance(template.package_gate, CompoundCondition):
        lines.extend(["**Gate:**", ""])
        lines.extend(_render_condition_lines(template.package_gate))
    else:
        lines.append(f"**Gate:** {_render_condition_block(template.package_gate)}")
    lines.append("")
    for i, branch in enumerate(template.branches, start=1):
        lines.extend(_render_branch(i, branch))
        lines.append("")
    return lines


# ---------------------------------------------------------------------------
# Vocabulary appendix
# ---------------------------------------------------------------------------


_VOCAB_PATTERNS: List[Tuple[str, re.Pattern]] = [
    ("durable_tag", re.compile(r"has_tag\(([^@()]+)@")),
    ("durable_tag", re.compile(r"lacks_tag\(([^@()]+)@")),
    ("durable_tag_list", re.compile(r"has_any_tag\(([^@()]+)@")),
    ("current_tag_list", re.compile(r"has_any_current_tag\(([^@()]+)@")),
    ("ephemeral_tag", re.compile(r"has_ephemeral\(([^@()]+)@")),
    ("pair_tag", re.compile(r"has_pair_tag\(([^@()]+)@")),
    ("pair_tag", re.compile(r"lacks_pair_tag\(([^@()]+)@")),
    ("pair_tag", re.compile(r"has_pair_tag_to_current_location\(([^@()]+)@")),
    ("pair_tag", re.compile(r"has_inbound_pair_tag\(([^@()]+)@")),
    ("pair_tag_list", re.compile(r"has_any_pair_tag\(([^@()]+)@")),
    ("contact_kind", re.compile(r"has_contact_of_kind\(([^@()]+)@")),
    ("event_type", re.compile(r"recent_event\(([^,*()]+),")),
    ("event_type", re.compile(r"knows_recent_event\(([^,*()]+),")),
    ("event_type", re.compile(r"since_last_event_at_least\(([^,()]+),")),
    ("place_class", re.compile(r"in_location_class\(([^@()]+)@")),
    ("place_class_list", re.compile(r"has_location_class_destination\(([^@()]+)@")),
    ("relationship", re.compile(r"has_relationship_of_type\(([^,()]+),")),
    (
        "relationship",
        re.compile(r"has_symmetric_relationship_of_type\(([^,()]+),"),
    ),
]


def _collect_vocabulary(
    templates: Iterable[Template],
) -> dict:
    """Walk templates collecting vocabulary by where it appears.

    Tags queried by gate/branch predicates are classified durable vs
    ephemeral by the predicate that queries them (has_tag → durable,
    has_ephemeral → ephemeral). Tags only appearing in state_delta
    effects are listed in a third "applied" bucket — their durable /
    ephemeral classification lives in the seeding migrations, not in
    the template source, so the renderer doesn't guess.
    """

    durable: set[str] = set()
    ephemeral: set[str] = set()
    current: set[str] = set()
    applied: set[str] = set()
    pair_tags: set[str] = set()
    events: set[str] = set()
    place_classes: set[str] = set()
    relationships: set[str] = set()

    def visit(condition: Any) -> None:
        if isinstance(condition, CompoundCondition):
            for child in condition.children:
                visit(child)
            return
        name = getattr(condition, "__name__", "")
        for kind, pattern in _VOCAB_PATTERNS:
            match = pattern.search(name)
            if not match:
                continue
            captured = match.group(1)
            if kind == "durable_tag":
                durable.add(captured)
            elif kind == "durable_tag_list":
                for tag in captured.split(","):
                    durable.add(tag.strip())
            elif kind == "current_tag_list":
                for tag in captured.split(","):
                    current.add(tag.strip())
            elif kind == "ephemeral_tag":
                ephemeral.add(captured)
            elif kind == "pair_tag":
                pair_tags.add(captured)
            elif kind == "pair_tag_list":
                for tag in captured.split(","):
                    pair_tags.add(tag.strip())
            elif kind == "contact_kind":
                pair_tags.add(f"contact:{captured}")
            elif kind == "event_type":
                events.add(captured)
            elif kind == "place_class":
                place_classes.add(captured)
            elif kind == "place_class_list":
                for tag in captured.split(","):
                    place_classes.add(tag.strip())
            elif kind == "relationship":
                relationships.add(captured)
            # First-match-wins: prevents future overlapping patterns from
            # silently double-classifying a predicate.
            break

    for template in templates:
        visit(template.package_gate)
        for branch in template.branches:
            visit(branch.conditions)
            if branch.event_type:
                events.add(branch.event_type)
            for key, value in branch.state_delta.items():
                if key in (
                    "entity_pair_tags_target.clear_inbound",
                    "entity_pair_tags.add_outbound",
                    "entity_pair_tags.clear_outbound",
                ):
                    if isinstance(value, list):
                        for tag in value:
                            pair_tags.add(str(tag))
                    continue
                if not key.startswith("entity_tags"):
                    continue
                if not isinstance(value, list):
                    continue
                for tag in value:
                    applied.add(tag)

    # Tags appearing in both query and apply contexts shouldn't be
    # duplicated; classification by query wins.
    applied -= durable
    applied -= ephemeral
    applied -= current

    return {
        "durable_tags": sorted(durable),
        "ephemeral_tags": sorted(ephemeral),
        "current_tags": sorted(current),
        "applied_tags": sorted(applied),
        "pair_tags": sorted(pair_tags),
        "event_types": sorted(events),
        "place_classes": sorted(place_classes),
        "relationship_types": sorted(relationships),
    }


def collect_template_vocabulary(templates: Iterable[Template]) -> dict:
    """Return package-facing vocabulary referenced by Orrery templates."""

    return _collect_vocabulary(templates)


def _discover_orrery_migrations() -> List[str]:
    """Find every migration file in migrations/ whose name mentions orrery.

    Globbed rather than hardcoded so renames (or net-new orrery vocabulary
    migrations) keep the catalog cross-reference accurate without manual
    edits. Returns paths relative to repo root, sorted lexically.
    """

    migrations_dir = Path(__file__).resolve().parents[3] / "migrations"
    if not migrations_dir.exists():
        return []
    candidates = sorted(migrations_dir.glob("*orrery*"))
    return [f"migrations/{path.name}" for path in candidates]


def _render_vocabulary_appendix(templates: Iterable[Template]) -> List[str]:
    vocab = _collect_vocabulary(templates)
    lines = [
        "## Vocabulary Reference",
        "",
        "Vocabulary referenced by the templates above. Cross-reference with",
        "the seeding migrations to confirm catalog ↔ schema agreement:",
        "",
    ]
    for migration_path in _discover_orrery_migrations():
        lines.append(f"- `{migration_path}`")
    lines.append("")
    sections = [
        (
            "Tags queried as durable (via `has_tag` / `lacks_tag` / " "`has_any_tag`)",
            vocab["durable_tags"],
        ),
        (
            "Tags queried as ephemeral (via `has_ephemeral`)",
            vocab["ephemeral_tags"],
        ),
        (
            "Tags queried as current durable-or-ephemeral state "
            "(via `has_any_current_tag`)",
            vocab["current_tags"],
        ),
        (
            "Tags applied by branch effects (durable vs ephemeral "
            "classification per migration)",
            vocab["applied_tags"],
        ),
        ("Pair tags queried by directed predicates", vocab["pair_tags"]),
        ("Event types", vocab["event_types"]),
        (
            "Place classes queried by location predicates",
            vocab["place_classes"],
        ),
        ("Relationship types", vocab["relationship_types"]),
    ]
    for heading, values in sections:
        if not values:
            continue
        lines.append(f"### {heading}")
        lines.append("")
        for value in values:
            lines.append(f"- `{value}`")
        lines.append("")
    return lines


# ---------------------------------------------------------------------------
# Top-level render + CLI
# ---------------------------------------------------------------------------


def render_catalog(templates: Iterable[Template]) -> str:
    """Render the full package catalog as a markdown string."""

    lines = [
        AUTO_GEN_HEADER,
        "",
        "# Orrery Package Catalog",
        "",
        "Behavior templates evaluated by the Orrery off-screen resolver, "
        "ordered by priority (highest first).",
        "",
        "Drive bands are authoring metadata: they explain whether a package is "
        "crisis/constraint, embodied maintenance, anchored routine, affiliation, "
        "or project/identity pressure. Static priority still decides resolver "
        "order; any lower-band package that outranks a higher-band package should "
        "carry an explicit rationale.",
        "",
        "**Source-of-truth:** `nexus/agents/orrery/templates.py` "
        "(`BUILTIN_TEMPLATES`).  ",
        "**Substrate:** `nexus/agents/orrery/substrate.py` "
        "(`Template`, `Branch`, `CompoundCondition`).  ",
        "**Design plan:** [docs/orrery_design_plan.md](orrery_design_plan.md)",
        "",
        "---",
        "",
    ]
    sorted_templates = sorted(templates, key=lambda t: -t.priority)
    warnings = drive_band_priority_warnings(sorted_templates)
    if warnings:
        lines.extend(
            [
                "## Drive-Band Priority Warnings",
                "",
                "These package priorities contradict the default drive-band order "
                "without an explicit rationale:",
                "",
            ]
        )
        for warning in warnings:
            lines.append(f"- {warning}")
        lines.extend(["", "---", ""])
    for template in sorted_templates:
        lines.extend(_render_template(template))
        lines.append("---")
        lines.append("")
    # Pass the already-materialized sorted list, not the original iterable:
    # sorted() exhausts a generator and the appendix would silently render
    # empty.
    lines.extend(_render_vocabulary_appendix(sorted_templates))
    return "\n".join(lines).rstrip() + "\n"


def _doc_path() -> Path:
    """Locate ``docs/orrery_packages.md`` relative to this module.

    catalog.py at nexus/agents/orrery/catalog.py → repo_root/docs/...
    parents[0]=orrery, [1]=agents, [2]=nexus, [3]=repo_root.
    """

    return Path(__file__).resolve().parents[3] / "docs" / "orrery_packages.md"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--write",
        action="store_true",
        help="Write the rendered catalog to docs/orrery_packages.md",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/orrery_packages.md differs from a fresh render",
    )
    args = parser.parse_args()
    content = render_catalog(BUILTIN_TEMPLATES)
    doc = _doc_path()
    if args.check:
        existing = doc.read_text() if doc.exists() else ""
        if existing != content:
            sys.stderr.write(
                "docs/orrery_packages.md is stale.\n"
                "Run: python -m nexus.agents.orrery.catalog --write\n"
            )
            sys.exit(1)
        return
    if args.write:
        doc.write_text(content)
        sys.stdout.write(f"Wrote {doc}\n")
    else:
        sys.stdout.write(content)


if __name__ == "__main__":
    main()
