#!/usr/bin/env python3
"""Apply reviewed slot 2 semantic tag proposals to ``entity_tags``.

The proposal manifest is generated by the separate slot-2 semantic backfill
workflow. This script is intentionally conservative: it only inserts current
tags that already exist in the slot database, skips low-confidence proposals by
default, and rejects categories that are not meaningful for the entity kind.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional

import psycopg2
from psycopg2.extras import DictCursor

from nexus.api.slot_utils import get_slot_db_url


DEFAULT_SLOT = 2
DEFAULT_MANIFEST = Path("temp/slot2_backfill/manifest.json")
DEFAULT_SOURCE_KIND = "llm_generated"

CONFIDENCE_RANK: Mapping[str, int] = {
    "low": 1,
    "medium": 2,
    "high": 3,
}

ALLOWED_CATEGORIES: Mapping[str, frozenset[str]] = {
    "character": frozenset(
        {
            "bodyform",
            "capacity",
            "disposition",
            "orrery_need_modifier",
            "orrery_signal",
            "orrery_state",
            "profession_lite",
            "role",
            "state",
        }
    ),
    "faction": frozenset(
        {
            "hidden_agenda_class",
            "history_class",
            "ideology_axis",
            "legitimacy_status",
            "operational_secrecy",
            "power_posture",
            "resource_class",
        }
    ),
    "place": frozenset({"place_affordance"}),
}

# Small, explicit canonicalization list from the reviewed slot 2 report. This
# keeps the live backfill useful without auto-collapsing every naming cluster.
CANONICAL_TAGS: Mapping[str, str] = {
    "bridge_linked": "bridge_aware",
    "captive_subject": "captive",
    "collapse_survivor": "trauma_survivor",
    "corporate_defector": "corporate_exile",
    "digital_consciousness": "digital_mind",
    "disaster_survivor": "trauma_survivor",
    "echo_survivor": "trauma_survivor",
    "estranged_parent": "parent",
    "ex_corporate": "corporate_exile",
    "found_family_anchor": "extended_household",
    "found_family_member": "extended_household",
    "shadow_broker": "broker",
    "trauma_history": "trauma_survivor",
}


@dataclass(frozen=True, slots=True)
class TagDefinition:
    """Registered tag metadata loaded from the target slot."""

    id: int
    category: str
    is_ephemeral: bool


@dataclass(frozen=True, slots=True)
class EntityDefinition:
    """Entity metadata loaded from the target slot."""

    kind: str
    name: str


@dataclass(frozen=True, slots=True)
class Candidate:
    """One approved proposal ready to insert unless already present."""

    entity_id: int
    entity_kind: str
    entity_name: str
    proposed_tag: str
    tag: str
    tag_id: int
    category: str
    confidence: str
    # Summary-only origin from the proposal manifest; database provenance is
    # the single entity_tag_source_kind supplied by --source-kind.
    proposal_source: str
    evidence: str


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="Path to slot2_backfill/manifest.json.",
    )
    parser.add_argument(
        "--slot",
        type=int,
        help=(
            "Target save slot. Defaults to NEXUS_SLOT when set, otherwise "
            f"slot {DEFAULT_SLOT}."
        ),
    )
    parser.add_argument(
        "--min-confidence",
        choices=tuple(CONFIDENCE_RANK),
        default="medium",
        help="Minimum proposal confidence to apply.",
    )
    parser.add_argument(
        "--source-kind",
        default=DEFAULT_SOURCE_KIND,
        help="entity_tag_source_kind to stamp on inserted rows.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write tags. Without this flag the script only reports a dry run.",
    )
    parser.add_argument(
        "--summary-json",
        type=Path,
        help="Optional path for a machine-readable dry-run/apply summary.",
    )
    return parser.parse_args()


def main() -> None:
    """Run the backfill application workflow."""

    args = parse_args()
    manifest = _load_manifest(args.manifest)
    database_url = _resolve_database_url(args.slot)

    conn = psycopg2.connect(database_url)
    try:
        with conn.cursor(cursor_factory=DictCursor) as cur:
            tags = _load_tags(cur)
            entities = _load_entities(cur)
            current = _load_current_tags(cur)
            source_kinds = _load_source_kinds(cur)
            world_time = _load_current_world_time(cur)

            if args.source_kind not in source_kinds:
                raise ValueError(
                    f"source kind {args.source_kind!r} is not registered; "
                    f"available={sorted(source_kinds)}"
                )

            candidates, skipped = _build_candidates(
                manifest,
                tags=tags,
                entities=entities,
                current=current,
                min_confidence=args.min_confidence,
            )

            if args.apply:
                inserted = _insert_candidates(
                    cur,
                    candidates,
                    current=current,
                    source_kind=args.source_kind,
                    world_time=world_time,
                )
                conn.commit()
            else:
                inserted = 0
                conn.rollback()

        summary = _summarize(
            candidates,
            skipped,
            inserted=inserted,
            apply=args.apply,
            manifest_path=args.manifest,
            database_url=database_url,
        )
        _print_summary(summary)
        if args.summary_json is not None:
            args.summary_json.parent.mkdir(parents=True, exist_ok=True)
            args.summary_json.write_text(
                json.dumps(summary, indent=2, sort_keys=True),
                encoding="utf-8",
            )
    finally:
        conn.close()


def _resolve_database_url(slot: Optional[int]) -> str:
    if slot is not None:
        return get_slot_db_url(slot=slot)
    try:
        return get_slot_db_url()
    except RuntimeError:
        return get_slot_db_url(slot=DEFAULT_SLOT)


def _load_manifest(path: Path) -> Mapping[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Slot 2 backfill manifest not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, Mapping) or not isinstance(data.get("per_entity"), list):
        raise ValueError("Manifest must contain a per_entity list")
    return data


def _load_tags(cur: DictCursor) -> dict[str, TagDefinition]:
    cur.execute(
        """
        SELECT id, tag, category, is_ephemeral
        FROM tags
        WHERE deprecated = FALSE
          AND synonym_for IS NULL
        """
    )
    return {
        row["tag"]: TagDefinition(
            id=int(row["id"]),
            category=str(row["category"]),
            is_ephemeral=bool(row["is_ephemeral"]),
        )
        for row in cur.fetchall()
    }


def _load_entities(cur: DictCursor) -> dict[int, EntityDefinition]:
    cur.execute(
        """
        SELECT id, kind::text AS kind, name
        FROM entity_names_v
        """
    )
    return {
        int(row["id"]): EntityDefinition(kind=str(row["kind"]), name=str(row["name"]))
        for row in cur.fetchall()
    }


def _load_current_tags(cur: DictCursor) -> set[tuple[int, int]]:
    cur.execute(
        """
        SELECT entity_id, tag_id
        FROM entity_tags
        WHERE cleared_at IS NULL
        """
    )
    return {(int(row["entity_id"]), int(row["tag_id"])) for row in cur.fetchall()}


def _load_source_kinds(cur: DictCursor) -> set[str]:
    cur.execute(
        """
        SELECT enumlabel
        FROM pg_enum
        JOIN pg_type ON pg_type.oid = pg_enum.enumtypid
        WHERE typname = 'entity_tag_source_kind'
        """
    )
    return {str(row["enumlabel"]) for row in cur.fetchall()}


def _load_current_world_time(cur: DictCursor) -> Optional[datetime]:
    cur.execute("SELECT max(world_time) AS world_time FROM chunk_metadata")
    row = cur.fetchone()
    if row is None:
        return None
    return row["world_time"]


def _build_candidates(
    manifest: Mapping[str, Any],
    *,
    tags: Mapping[str, TagDefinition],
    entities: Mapping[int, EntityDefinition],
    current: set[tuple[int, int]],
    min_confidence: str,
) -> tuple[list[Candidate], Counter[str]]:
    skipped: Counter[str] = Counter()
    deduped: dict[tuple[int, int], Candidate] = {}
    minimum = CONFIDENCE_RANK[min_confidence]

    for entity in manifest["per_entity"]:
        entity_id = int(entity["entity_id"])
        entity_kind = str(entity["entity_kind"])
        entity_name = str(entity["entity_name"])
        target = entities.get(entity_id)
        if target is None:
            skipped["missing_entity"] += _proposal_count(entity)
            continue
        if target.kind != entity_kind:
            raise ValueError(
                f"Manifest entity {entity_id} kind={entity_kind!r} does not "
                f"match database kind={target.kind!r}"
            )

        for proposal_source, proposal in _iter_proposals(entity):
            confidence = str(proposal.get("confidence") or "unknown")
            if CONFIDENCE_RANK.get(confidence, 0) < minimum:
                skipped["below_confidence"] += 1
                continue

            proposed_tag = str(proposal["tag"])
            tag_name = CANONICAL_TAGS.get(proposed_tag, proposed_tag)
            tag = tags.get(tag_name)
            if tag is None:
                skipped["unknown_tag"] += 1
                continue

            allowed = ALLOWED_CATEGORIES.get(entity_kind, frozenset())
            if tag.category not in allowed:
                skipped[f"incompatible_category:{tag.category}"] += 1
                continue

            key = (entity_id, tag.id)
            if key in current:
                skipped["already_current"] += 1
                continue

            candidate = Candidate(
                entity_id=entity_id,
                entity_kind=entity_kind,
                entity_name=target.name or entity_name,
                proposed_tag=proposed_tag,
                tag=tag_name,
                tag_id=tag.id,
                category=tag.category,
                confidence=confidence,
                proposal_source=proposal_source,
                evidence=str(proposal.get("evidence") or ""),
            )
            previous = deduped.get(key)
            if previous is None or _confidence_value(candidate) > _confidence_value(
                previous
            ):
                deduped[key] = candidate
            else:
                skipped["duplicate_not_higher_confidence"] += 1

    return (sorted(deduped.values(), key=_candidate_sort_key), skipped)


def _iter_proposals(
    entity: Mapping[str, Any],
) -> Iterable[tuple[str, Mapping[str, Any]]]:
    for proposal in entity.get("registered_tag_proposals", []):
        yield ("registered", proposal)
    for proposal in entity.get("new_tag_proposals", []):
        yield ("new", proposal)


def _proposal_count(entity: Mapping[str, Any]) -> int:
    return len(entity.get("registered_tag_proposals", [])) + len(
        entity.get("new_tag_proposals", [])
    )


def _confidence_value(candidate: Candidate) -> int:
    return CONFIDENCE_RANK.get(candidate.confidence, 0)


def _candidate_sort_key(candidate: Candidate) -> tuple[str, str, str, int]:
    return (
        candidate.entity_kind,
        candidate.entity_name.lower(),
        candidate.tag,
        candidate.tag_id,
    )


def _insert_candidates(
    cur: DictCursor,
    candidates: Iterable[Candidate],
    *,
    current: set[tuple[int, int]],
    source_kind: str,
    world_time: Optional[datetime],
) -> int:
    inserted = 0
    seen = set(current)
    for candidate in candidates:
        key = (candidate.entity_id, candidate.tag_id)
        if key in seen:
            continue
        cur.execute(
            """
            INSERT INTO entity_tags (
                entity_id,
                tag_id,
                applied_at_world_time,
                source_kind
            )
            VALUES (
                %s,
                %s,
                %s,
                %s::entity_tag_source_kind
            )
            ON CONFLICT (entity_id, tag_id)
              WHERE cleared_at IS NULL
              DO NOTHING
            """,
            (candidate.entity_id, candidate.tag_id, world_time, source_kind),
        )
        if cur.rowcount:
            inserted += 1
            seen.add(key)
    return inserted


def _summarize(
    candidates: list[Candidate],
    skipped: Counter[str],
    *,
    inserted: int,
    apply: bool,
    manifest_path: Path,
    database_url: str,
) -> dict[str, Any]:
    by_kind = Counter(candidate.entity_kind for candidate in candidates)
    by_category = Counter(candidate.category for candidate in candidates)
    by_confidence = Counter(candidate.confidence for candidate in candidates)
    by_source = Counter(candidate.proposal_source for candidate in candidates)
    canonicalized = [
        {
            "entity_id": candidate.entity_id,
            "entity": candidate.entity_name,
            "proposed_tag": candidate.proposed_tag,
            "tag": candidate.tag,
        }
        for candidate in candidates
        if candidate.proposed_tag != candidate.tag
    ]
    sample = [
        {
            "entity_id": candidate.entity_id,
            "entity_kind": candidate.entity_kind,
            "entity": candidate.entity_name,
            "tag": candidate.tag,
            "confidence": candidate.confidence,
            "category": candidate.category,
        }
        for candidate in candidates[:25]
    ]
    return {
        "mode": "apply" if apply else "dry_run",
        "database_url": database_url,
        "manifest": str(manifest_path),
        "candidate_count": len(candidates),
        "inserted_count": inserted,
        "skipped": dict(sorted(skipped.items())),
        "by_kind": dict(sorted(by_kind.items())),
        "by_category": dict(sorted(by_category.items())),
        "by_confidence": dict(sorted(by_confidence.items())),
        "by_proposal_source": dict(sorted(by_source.items())),
        "canonicalized_count": len(canonicalized),
        "canonicalized": canonicalized,
        "sample": sample,
    }


def _print_summary(summary: Mapping[str, Any]) -> None:
    print(f"Mode: {summary['mode']}")
    print(f"Database: {summary['database_url']}")
    print(f"Manifest: {summary['manifest']}")
    print(f"Candidates: {summary['candidate_count']}")
    print(f"Inserted: {summary['inserted_count']}")
    print(f"By kind: {summary['by_kind']}")
    print(f"By category: {summary['by_category']}")
    print(f"By confidence: {summary['by_confidence']}")
    print(f"By proposal source: {summary['by_proposal_source']}")
    print(f"Canonicalized: {summary['canonicalized_count']}")
    print(f"Skipped: {summary['skipped']}")


if __name__ == "__main__":
    main()
