"""Render the NEXUS CLI reference as markdown from the parser and its contract.

``nexus.cli.build_parser()`` is the source of truth for every command and its
arguments; ``nexus/cli_contract.py`` is the source of truth for each command's
transport. This module walks the parser's actions (never argparse's help
formatter, whose output depends on the terminal width and the program name)
and emits ``docs/cli_reference.md``.

Usage:
    python -m scripts.render_cli_reference            # render to stdout
    python -m scripts.render_cli_reference --write    # update docs/
    python -m scripts.render_cli_reference --check    # exit 1 if stale

Run it with the ``-m`` form from the checkout whose parser you mean to render:
``scripts/__init__.py`` makes ``nexus`` import from the current directory.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, List, Mapping, Optional, Sequence, Tuple

from nexus.cli import build_parser
from nexus.cli_contract import (
    COMMAND_TRANSPORTS,
    FLAG_TRANSPORTS,
    REMOTE_PROFILE_TRANSPORTS,
    TRANSPORT_OPENS,
    Transport,
    iter_command_parsers,
    iter_command_paths,
)

AUTO_GEN_HEADER = (
    "<!-- AUTO-GENERATED by scripts/render_cli_reference.py "
    "— do not edit by hand. -->\n"
    "<!-- Regenerate via: python -m scripts.render_cli_reference --write -->"
)

INTRO = (
    "Every command that `nexus.cli.build_parser()` registers, with its arguments "
    "and its transport from `nexus/cli_contract.py`. The guide, the exit codes, "
    "and the JSON envelopes are in [docs/cli.md](cli.md)."
)

ARGUMENT_TABLE_HEADER = (
    "| Argument | Takes | Default | Description |\n| --- | --- | --- | --- |"
)
TRANSPORT_TABLE_HEADER = "| Transport | Opens | Commands |\n| --- | --- | --- |"
DASH = "—"

FlagTransports = Mapping[str, Tuple[Tuple[str, Transport], ...]]


def _code(text: str) -> str:
    """Wrap text in backticks."""
    return f"`{text}`"


def _sentence(text: str) -> str:
    """One line of help text, ending with a period."""
    line = text.replace("\n", " ").strip()
    return line if line.endswith(".") else f"{line}."


def _is_subparsers(action: argparse.Action) -> bool:
    """Whether the action is a parser's subcommand action."""
    return isinstance(action, argparse._SubParsersAction)


def _rendered_actions(
    parser: argparse.ArgumentParser,
    root_options: Sequence[List[str]],
) -> List[argparse.Action]:
    """The parser's actions that get a table row, in action order."""
    rows = []
    for action in parser._actions:
        if isinstance(action, argparse._HelpAction) or _is_subparsers(action):
            continue
        if action.help is argparse.SUPPRESS:
            continue
        if action.option_strings and list(action.option_strings) in root_options:
            continue
        rows.append(action)
    return rows


def _argument_cell(action: argparse.Action) -> str:
    """The Argument cell: a positional's name or an option's strings."""
    if not action.option_strings:
        name = action.metavar if isinstance(action.metavar, str) else action.dest
        return _code(name)
    cell = ", ".join(_code(option) for option in action.option_strings)
    if action.required:
        cell += " (required)"
    return cell


def _takes_cell(action: argparse.Action, path: str) -> str:
    """The Takes cell: what value the argument takes, if any."""
    if action.nargs not in (None, 0, "?"):
        raise ValueError(
            f"nexus {path}: argument {action.dest!r} has nargs={action.nargs!r}; "
            "the reference renders only None, 0 and '?'"
        )
    if action.nargs == 0:
        return DASH
    if action.choices:
        cell = ", ".join(_code(str(choice)) for choice in action.choices)
    elif isinstance(action.metavar, str):
        cell = _code(action.metavar)
    elif action.option_strings:
        cell = _code(action.dest.upper())
    else:
        cell = _code(action.dest)
    if action.nargs == "?":
        cell += " (optional)"
    return cell


def _default_cell(action: argparse.Action) -> str:
    """The Default cell; ``0`` is a real default, ``False`` and None are not."""
    default: Any = action.default
    if default is None or default is False or default is argparse.SUPPRESS:
        return DASH
    return _code(str(default))


def _description_cell(action: argparse.Action) -> str:
    """The Description cell: the help on one line with pipes escaped."""
    if not action.help:
        return DASH
    return action.help.replace("\n", " ").replace("|", "\\|")


def _argument_table(actions: Sequence[argparse.Action], path: str) -> List[str]:
    """The argument table block of a parser's rows."""
    lines = [ARGUMENT_TABLE_HEADER]
    for action in actions:
        cells = (
            _argument_cell(action),
            _takes_cell(action, path),
            _default_cell(action),
            _description_cell(action),
        )
        lines.append("| " + " | ".join(cells) + " |")
    return ["\n".join(lines)]


def _flag_option(parser: argparse.ArgumentParser, path: str, dest: str) -> str:
    """The first ``--`` option string of the command's action named ``dest``."""
    for action in parser._actions:
        if action.dest != dest:
            continue
        for option in action.option_strings:
            if option.startswith("--"):
                return option
    raise ValueError(
        f"nexus {path}: flag_transports names {dest!r}, which has no -- option"
    )


def _group_member(action: argparse.Action) -> str:
    """A mutually exclusive group member: its first ``--`` option string."""
    for option in action.option_strings:
        if option.startswith("--"):
            return _code(option)
    if action.option_strings:
        return _code(action.option_strings[0])
    return _code(action.metavar if isinstance(action.metavar, str) else action.dest)


def _exclusive_lines(parser: argparse.ArgumentParser) -> List[str]:
    """One block per mutually exclusive group of the parser."""
    blocks = []
    for group in parser._mutually_exclusive_groups:
        lead = "Exactly one of " if group.required else "At most one of "
        members = ", ".join(_group_member(action) for action in group._group_actions)
        blocks.append(f"{lead}{members}.")
    return blocks


def _transport_line(
    path: str,
    parser: argparse.ArgumentParser,
    command_transports: Mapping[str, Transport],
    flag_transports: FlagTransports,
    remote_profile_transports: Mapping[str, Transport],
) -> str:
    """A leaf's transport line: base, per-flag, and remote-profile transports."""
    if path not in command_transports:
        raise ValueError(f"nexus {path}: no command_transports entry")
    parts = [f"Transport: {_code(command_transports[path])}."]
    for dest, transport in flag_transports.get(path, ()):
        flag = _flag_option(parser, path, dest)
        parts.append(f"With {_code(flag)}: {_code(transport)}.")
    remote = remote_profile_transports.get(path)
    if remote is not None:
        parts.append(f"Under the remote profile: {_code(remote)}.")
    return " ".join(parts)


def _transports_section(
    root: argparse.ArgumentParser,
    parsers: Mapping[str, argparse.ArgumentParser],
    command_transports: Mapping[str, Transport],
    flag_transports: FlagTransports,
    remote_profile_transports: Mapping[str, Transport],
) -> List[str]:
    """The Transports section: the table and the remote-profile line."""
    leaves = list(iter_command_paths(root))
    for path in leaves:
        if path not in command_transports:
            raise ValueError(f"nexus {path}: no command_transports entry")
    rows = [TRANSPORT_TABLE_HEADER]
    for transport, opens in TRANSPORT_OPENS.items():
        commands = [
            _code(path) for path in leaves if command_transports[path] == transport
        ]
        for path, variants in flag_transports.items():
            if path not in parsers:
                raise ValueError(f"nexus {path}: flag_transports names no command")
            for dest, variant_transport in variants:
                flag = _flag_option(parsers[path], path, dest)
                if variant_transport == transport:
                    commands.append(_code(f"{path} {flag}"))
        rows.append(f"| {_code(transport)} | {opens} | {', '.join(commands)} |")
    remote = "; ".join(
        f"{_code(path)} uses {_code(transport)}"
        for path, transport in remote_profile_transports.items()
    )
    return ["## Transports", "\n".join(rows), f"Under the remote profile: {remote}."]


def render_cli_reference(
    parser: argparse.ArgumentParser,
    *,
    command_transports: Mapping[str, Transport] = COMMAND_TRANSPORTS,
    flag_transports: FlagTransports = FLAG_TRANSPORTS,
    remote_profile_transports: Mapping[str, Transport] = REMOTE_PROFILE_TRANSPORTS,
) -> str:
    """Render the CLI reference markdown from the parser's actions.

    Raises:
        ValueError: A leaf has no ``command_transports`` entry, a subparser has
            no help, an argument's ``nargs`` is not None, 0 or ``"?"``, or a
            ``flag_transports`` destination has no ``--`` option string.
    """
    entries = list(iter_command_parsers(parser))
    parsers = {path: child for path, child, _help in entries}
    root_actions = _rendered_actions(parser, ())
    root_option_strings = [
        list(action.option_strings)
        for action in parser._actions
        if action.option_strings
    ]

    blocks: List[str] = [AUTO_GEN_HEADER, "# NEXUS CLI Reference", INTRO]
    blocks.append("## Global Options")
    blocks.extend(_argument_table(root_actions, "(global options)"))
    blocks.extend(
        _transports_section(
            parser,
            parsers,
            command_transports,
            flag_transports,
            remote_profile_transports,
        )
    )

    blocks.append("## Commands")
    for path, child, help_text in entries:
        if not help_text:
            raise ValueError(f"nexus {path}: the subparser has no help")
        blocks.append(f"### `nexus {path}`")
        blocks.append(_sentence(help_text))
        verbs = _verbs(child, path)
        if verbs is not None:
            blocks.append(f"Verbs: {', '.join(verbs)}.")
            continue
        blocks.append(
            _transport_line(
                path,
                child,
                command_transports,
                flag_transports,
                remote_profile_transports,
            )
        )
        rows = _rendered_actions(child, root_option_strings)
        if rows:
            blocks.extend(_argument_table(rows, path))
        else:
            blocks.append("No arguments.")
        blocks.extend(_exclusive_lines(child))
    return "\n\n".join(blocks).rstrip() + "\n"


def _verbs(parser: argparse.ArgumentParser, path: str) -> Optional[List[str]]:
    """A group's verbs as ``nexus <path> <verb>`` code spans, or None for a leaf."""
    for action in parser._actions:
        if _is_subparsers(action):
            assert isinstance(action.choices, dict)
            return [_code(f"nexus {path} {name}") for name in action.choices]
    return None


def _doc_path() -> Path:
    """Locate ``docs/cli_reference.md``: scripts/ → repo root → docs/."""
    return Path(__file__).resolve().parents[1] / "docs" / "cli_reference.md"


def main() -> None:
    """Render, write, or check ``docs/cli_reference.md``."""
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--write",
        action="store_true",
        help="Replace docs/cli_reference.md with a fresh render",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if docs/cli_reference.md differs from a fresh render",
    )
    args = parser.parse_args()
    content = render_cli_reference(build_parser())
    doc = _doc_path()
    if args.check:
        existing = doc.read_text() if doc.exists() else ""
        if existing != content:
            sys.stderr.write(
                "docs/cli_reference.md is stale.\n"
                "Run: python -m scripts.render_cli_reference --write\n"
            )
            sys.exit(1)
        return
    if args.write:
        doc.write_text(content)
        sys.stdout.write(f"Wrote {doc}\n")
    else:
        sys.stdout.write(content)


if __name__ == "__main__":
    main()
