/**
 * Art Deco frames — measured multi-band slicing geometry.
 *
 * Auto-measured stretch zones per frame (TRUE extents, no averaging) for the
 * nine licensed frames in this directory (Adobe Stock 549888080; see
 * LICENSE.md). `cols`/`rows` are track boundaries in source pixels;
 * `colStretch`/`rowStretch` flag the pure straight bands that may extend
 * without distortion; `colInkC`/`rowInkC` are per-band ink bounding-box
 * centers (null for stretch bands) used by the layout solver to place
 * ornaments at mirror-symmetric output positions.
 *
 * Do NOT replace consumers with naive CSS border-image 9-slice: uniform slice
 * values distort the corner and center ornaments. Generated by the NEXUS IRIS
 * design handoff (design_handoff/project/ui_kits/nexus_iris/frames_meta.js).
 */

export interface DecoFrameMeta {
  /** Source raster width in pixels. */
  w: number;
  /** Source raster height in pixels. */
  h: number;
  /** Column track boundaries in source pixels (length = bands + 1). */
  cols: number[];
  /** Per-column-band flag: true = straight band, safe to stretch. */
  colStretch: boolean[];
  /** Per-column-band ink bbox center (null for stretch bands). */
  colInkC: (number | null)[];
  /** Row track boundaries in source pixels (length = bands + 1). */
  rows: number[];
  /** Per-row-band flag: true = straight band, safe to stretch. */
  rowStretch: boolean[];
  /** Per-row-band ink bbox center (null for stretch bands). */
  rowInkC: (number | null)[];
}

export const DECO_FRAME_META: Record<string, DecoFrameMeta> = {"r1c1":{"w":1732,"h":1077,"cols":[0,404,622,1080,1305,1732],"colStretch":[false,true,false,true,false],"colInkC":[203,null,851,null,1528],"rows":[0,238,293,784,839,1077],"rowStretch":[false,true,false,true,false],"rowInkC":[159,null,538,null,917]},"r1c2":{"w":1670,"h":1060,"cols":[0,401,622,733,938,1048,1269,1670],"colStretch":[false,true,false,true,false,true,false],"colInkC":[187.5,null,677.5,null,993,null,1481.5],"rows":[0,406,654,1060],"rowStretch":[false,true,false],"rowInkC":[187.5,null,871.5]},"r1c3":{"w":1688,"h":1051,"cols":[0,307,523,1155,1381,1688],"colStretch":[false,true,false,true,false],"colInkC":[84.5,null,838,null,1602.5],"rows":[0,343,710,1051],"rowStretch":[false,true,false],"rowInkC":[119.5,null,930.5]},"r2c1":{"w":1732,"h":1065,"cols":[0,312,576,819,973,1206,1427,1732],"colStretch":[false,true,false,true,false,true,false],"colInkC":[139,null,697.5,null,1089.5,null,1592],"rows":[0,353,712,1065],"rowStretch":[false,true,false],"rowInkC":[152,null,912]},"r2c2":{"w":1678,"h":1051,"cols":[0,269,382,486,729,944,1192,1298,1409,1678],"colStretch":[false,true,false,true,false,true,false,true,false],"colInkC":[130,null,412,null,835.5,null,1266.5,null,1547],"rows":[0,259,322,402,449,602,650,729,792,1051],"rowStretch":[false,true,false,true,false,true,false,true,false],"rowInkC":[130,null,362,null,525,null,689.5,null,920]},"r2c3":{"w":1660,"h":1053,"cols":[0,464,647,992,1196,1660],"colStretch":[false,true,false,true,false],"colInkC":[219.5,null,817,null,1439.5],"rows":[0,459,597,1053],"rowStretch":[false,true,false],"rowInkC":[219.5,null,832.5]},"r3c1":{"w":1720,"h":1051,"cols":[0,571,1152,1720],"colStretch":[false,true,false],"colInkC":[238,null,1481],"rows":[0,483,571,1051],"rowStretch":[false,true,false],"rowInkC":[232.5,null,817.5]},"r3c2":{"w":1671,"h":1051,"cols":[0,362,635,1034,1310,1671],"colStretch":[false,true,false,true,false],"colInkC":[86.5,null,834,null,1583.5],"rows":[0,295,350,432,619,702,756,1051],"rowStretch":[false,true,false,true,false,true,false],"rowInkC":[148.5,null,391,null,660.5,null,901.5]},"r3c3":{"w":1669,"h":1056,"cols":[0,404,502,639,1032,1168,1267,1669],"colStretch":[false,true,false,true,false,true,false],"colInkC":[192.5,null,536,null,1132.5,null,1475.5],"rows":[0,452,606,1056],"rowStretch":[false,true,false],"rowInkC":[212,null,842.5]}};
